[counts]
critical = 0
critical_resolved = 0
critical_acknowledged = 0
high = 0
high_resolved = 0
high_acknowledged = 0
medium = 0
medium_resolved = 0
medium_acknowledged = 0
low = 0
low_resolved = 0
low_acknowledged = 0
informational = 0
informational_resolved = 0
informational_acknowledged = 0
gas_optimization = 0
gas_optimization_resolved = 0
gas_optimization_acknowledged = 0
total = 0
total_resolved = 0
total_acknowledged = 0
